# Render service + optional Postgres DB configuration
services:
  - type: web
    name: loyalilnk-login
    env: python3
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --workers 2 --worker-class sync --bind 0.0.0.0:10000 wsgi:app
    envVars:
      - key: SECRET_KEY
        value: ""
      - key: DATABASE_URL
        value: ""

databases:
  - name: loyalilnk-db
    engine: postgres
    plan: starter
